import test from 'node:test'
import assert from 'node:assert/strict'
import { spawn } from 'node:child_process'
import { mkdtemp, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { once } from 'node:events'
import { hashPassword } from '../server/lib/auth.js'
import * as XLSX from 'xlsx'

test('procurement API regression checks on isolated data', async (t) => {
  const data = await mkdtemp(join(tmpdir(), 'opro-regression-'))
  const port = 44123
  const adminPassword = 'test-only-admin-password-123'
  const server = spawn(process.execPath, ['server/index.js'], { env: { ...process.env, PORT: String(port), RFQ_DATA_DIR: data, OPENAI_API_KEY: '', ADMIN_BOOTSTRAP_USERNAME: 'admin', ADMIN_BOOTSTRAP_PASSWORD_HASH: await hashPassword(adminPassword), ACCOUNT_PASSWORD_ENCRYPTION_KEY: Buffer.alloc(32, 7).toString('base64url') }, stdio: ['ignore', 'pipe', 'pipe'] })
  let output = ''
  server.stdout.on('data', (x) => { output += x })
  server.stderr.on('data', (x) => { output += x })
  t.after(async () => { const exited = once(server, 'exit'); server.kill(); await exited; await rm(data, { recursive: true, force: true }) })
  let adminCookie = ''
  const request = async (path, body, method = 'POST', cookie = adminCookie, extraHeaders = {}) => {
    const res = await fetch(`http://localhost:${port}/api${path}`, { method, headers: { 'Content-Type': 'application/json', 'x-opro-request': '1', ...(cookie ? { Cookie: cookie } : {}), ...extraHeaders }, ...(method === 'GET' ? {} : { body: JSON.stringify(body || {}) }) })
    return { status: res.status, data: res.status === 204 ? null : await res.json(), requestId: res.headers.get('x-request-id') }
  }
  for (let i = 0; i < 100; i++) {
    try { if ((await request('/health', null, 'GET')).status === 200) break } catch {}
    if (server.exitCode != null || i === 99) throw new Error(output || 'API did not start')
    await new Promise((resolve) => setTimeout(resolve, 100))
  }
  const login = async (username, password) => {
    const res = await fetch(`http://localhost:${port}/api/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json', 'x-opro-request': '1' }, body: JSON.stringify({ username, password }) })
    return { status: res.status, data: await res.json(), cookie: res.headers.get('set-cookie')?.split(';')[0] || '' }
  }
  assert.equal((await request('/roles', null, 'GET', '')).status, 401)
  assert.equal((await request('/roles', null, 'GET', '', { 'x-role-key': 'admin' })).status, 401)
  assert.equal((await login('admin', 'wrong-password')).status, 401)
  const signedIn = await login('admin', adminPassword)
  assert.equal(signedIn.status, 200)
  adminCookie = signedIn.cookie
  assert.ok(adminCookie.startsWith('opro_session='))
  assert.equal((await request('/auth/me', null, 'GET')).data.account.username, 'admin')
  assert.equal((await request('/roles', {}, 'POST', adminCookie, { 'x-opro-request': '0' })).status, 403)
  let rfq
  await t.test('catalogue fields, full-catalogue search, pagination and metadata', async () => {
    const fields = { name: 'Catalogue source fixture', aiName: 'AI-UNIQUE-LOOKUP', description: 'Full description', sku: '00042', category: 'Custom category', subcategory: 'Custom subcategory', uom: '', partNo: 'MPN-UNIQUE-LOOKUP', unitName: 'Source unit' }
    const added = await request('/items', fields)
    assert.equal(added.status, 201)
    for (const [key, value] of Object.entries(fields)) assert.equal(added.data.item[key], value)
    const search = await request('/items?paged=true&q=AI-UNIQUE-LOOKUP', null, 'GET')
    assert.equal(search.data.total, 1)
    assert.equal(search.data.items[0].sku, '00042')
    assert.equal((await request('/items?paged=true&q=MPN-UNIQUE-LOOKUP&offset=1', null, 'GET')).data.items.length, 0)
    const meta = await request('/items/meta', null, 'GET')
    assert.ok(meta.data.categories.includes('Custom category'))
    assert.ok(meta.data.subcategories.includes('Custom subcategory'))
    await request(`/items/${added.data.item.id}`, { aiName: 'Edited AI', subcategory: 'Edited subcategory', unitName: '' }, 'PUT')
    const edited = await request('/items?paged=true&q=Edited%20AI', null, 'GET')
    assert.equal(edited.data.items[0].unitName, '')
    assert.equal(edited.data.items[0].subcategory, 'Edited subcategory')
  })
  await t.test('admin manages the RFQ currency list', async () => {
    const initial = await request('/currencies', null, 'GET')
    assert.equal(initial.status, 200)
    assert.deepEqual(initial.data.map((item) => item.code), ['AED', 'AUD', 'CAD', 'CNY', 'EUR', 'GBP', 'INR', 'JPY', 'LKR', 'MVR', 'SAR', 'SGD', 'THB', 'USD', 'ZAR'])
    assert.equal((await request('/currencies/USD', { active: false }, 'PUT')).status, 400)
    const added = await request('/currencies', { code: 'nzd', name: 'New Zealand dollar' })
    assert.equal(added.status, 201)
    assert.equal(added.data.code, 'NZD')
    assert.equal((await request('/currencies', { code: 'NZD', name: 'Duplicate' })).status, 409)
    assert.equal((await request('/currencies/NZD', { active: false }, 'PUT')).data.active, false)
    assert.equal((await request('/rfqs', { title: 'Inactive currency', currency: 'NZD' })).status, 400)
    assert.equal((await request('/currencies/NZD', { active: true }, 'PUT')).data.active, true)
    assert.equal((await request('/rfqs', { title: 'Active currency', currency: 'NZD', lines: [{ name: 'Test', qty: 1 }] })).status, 201)
  })
  await t.test('roles share permissions while users keep individual credentials', async () => {
    const cookies = new Map()
    const asUser = (path, user, body, method = body ? 'POST' : 'GET') => request(path, body, method, cookies.get(user) || '', { 'x-role-key': user, 'x-supplier-id': 'SUP-002' })
    assert.equal((await request('/roles', null, 'GET')).data.length, 1)
    assert.equal((await request('/users', null, 'GET')).data.length, 1)
    const role = await request('/roles', { label: 'Restricted Reviewer #1', permissions: ['workspace.view', 'rfq.evaluate'] })
    assert.equal(role.status, 201)
    assert.ok(!('username' in role.data) && !('passwordHash' in role.data))
    const first = await request('/users', { roleId: role.data.id, username: 'reviewer', password: 'reviewer-password-123', readOnly: true })
    assert.equal(first.status, 201)
    const second = await request('/users', { roleId: role.data.id, username: '  Second Reviewer #2  ', password: 'reviewer2-password-123' })
    assert.equal(second.status, 201)
    const portalRole = await request(`/roles/${role.data.id}`, { ...role.data, permissions: [...role.data.permissions, 'portal.access', 'quote.submit'] }, 'PUT')
    assert.equal(portalRole.status, 200)
    assert.equal(portalRole.data.permissions.includes('portal.access'), true)
    assert.equal(second.data.supplierId, '')
    assert.equal(second.data.username, 'second reviewer #2')
    assert.equal((await login('SECOND REVIEWER #2', 'reviewer2-password-123')).status, 200)
    assert.equal((await request('/roles', null, 'GET')).data.length, 2)
    assert.equal((await request('/users', null, 'GET')).data.length, 3)
    assert.equal((await request(`/users/${first.data.id}/password`, null, 'GET', '')).status, 401)
    for (let attempt = 0; attempt < 2; attempt++) {
      const revealed = await request(`/users/${first.data.id}/password`, null, 'GET')
      assert.deepEqual(revealed.data, { username: 'reviewer', password: 'reviewer-password-123' })
    }
    assert.ok(!JSON.stringify((await request('/users', null, 'GET')).data).includes('reviewer-password-123'))
    cookies.set('reviewer', (await login('reviewer', 'reviewer-password-123')).cookie)
    cookies.set('reviewer2', (await login('second reviewer #2', 'reviewer2-password-123')).cookie)
    assert.equal((await request('/auth/me', null, 'GET', cookies.get('reviewer2'))).data.account.permissions.includes('portal.access'), true)
    assert.equal((await asUser(`/users/${first.data.id}/password`, 'reviewer')).status, 403)
    assert.equal((await asUser('/rfqs', 'reviewer')).status, 200)
    assert.equal((await asUser('/notifications/read-all', 'reviewer', {})).status, 200)
    assert.equal((await asUser('/rfqs', 'reviewer', { title: 'Denied' })).status, 403)
    assert.equal((await asUser('/reports', 'reviewer')).status, 403)
    assert.equal((await asUser('/reports', 'reviewer2')).status, 403)
    assert.equal((await request(`/roles/${role.data.id}`, { ...portalRole.data, permissions: [...portalRole.data.permissions, 'reports.view'] }, 'PUT')).status, 200)
    assert.equal((await asUser('/reports', 'reviewer')).status, 200)
    assert.equal((await asUser('/reports', 'reviewer2')).status, 200)
    assert.equal((await request(`/roles/${role.data.id}`, role.data, 'PUT')).status, 409)
    assert.equal((await request(`/roles/${role.data.id}`, null, 'DELETE')).status, 409)
    assert.equal((await request('/roles/admin', { label: 'Changed', permissions: [], version: 1 }, 'PUT')).status, 403)
    assert.equal((await asUser('/roles', 'reviewer', { label: 'Escalation', permissions: [] })).status, 403)
    const updatedRole = (await request('/roles', null, 'GET')).data.find((item) => item.id === role.data.id)
    assert.equal((await request(`/roles/${role.data.id}`, { ...updatedRole, enabled: false }, 'PUT')).status, 200)
    assert.equal((await asUser('/rfqs', 'reviewer')).status, 401)
    assert.equal((await asUser('/rfqs', 'reviewer2')).status, 401)
    const supplierRole = await request('/roles', { label: 'Supplier account', permissions: ['portal.access', 'quote.submit'] })
    assert.equal(supplierRole.status, 201)
    const unlinked = await request('/users', { roleId: supplierRole.data.id, username: 'portalstaff', password: 'portal-password-123' })
    assert.equal(unlinked.status, 201)
    const unlinkedCookie = (await login('portalstaff', 'portal-password-123')).cookie
    assert.equal((await request('/rfqs/RFQ-2026-0041', null, 'GET', unlinkedCookie)).status, 200)
    assert.ok((await request('/rfqs', null, 'GET', unlinkedCookie)).data.length > 1)
    const supplier = await request('/users', { roleId: supplierRole.data.id, username: 'supplier01', password: 'supplier-password-123', supplierId: 'SUP-001' })
    assert.equal(supplier.status, 201)
    cookies.set('supplier', (await login('supplier01', 'supplier-password-123')).cookie)
    const own = await asUser('/rfqs/RFQ-2026-0042', 'supplier')
    assert.equal(own.status, 200)
    assert.ok(own.data.quotes.every((q) => q.supplierId === 'SUP-001'))
    assert.equal((await asUser('/rfqs/RFQ-2026-0041', 'supplier')).status, 403)
    assert.equal((await asUser('/rfqs/RFQ-2026-0042/quote', 'supplier', { supplierId: 'SUP-002' })).status, 403)
    const authorRole = await request('/roles', { label: 'Draft Author', permissions: ['workspace.view', 'rfq.create'] })
    const author = await request('/users', { roleId: authorRole.data.id, username: 'author', password: 'author-password-123' })
    cookies.set('author', (await login('author', 'author-password-123')).cookie)
    const draft = await asUser('/rfqs', 'author', { title: 'Draft only', lines: [{ name: 'Lamp', qty: 1 }] })
    assert.equal(draft.status, 201)
    assert.equal((await asUser(`/rfqs/${draft.data.id}/assign`, 'author', { supplierId: 'SUP-001' })).status, 200)
    assert.equal((await asUser(`/rfqs/${draft.data.id}`, 'author', null, 'GET')).data.status, 'Draft')
    assert.equal((await asUser(`/rfqs/${draft.data.id}/status`, 'author', { status: 'Published' })).status, 403)
    const reset = await request(`/users/${author.data.id}`, { ...author.data, password: 'new-author-password-123' }, 'PUT')
    assert.equal(reset.status, 200)
    assert.equal((await request(`/users/${author.data.id}/password`, null, 'GET')).data.password, 'new-author-password-123')
    assert.equal((await asUser('/rfqs', 'author')).status, 401)
    assert.equal((await login('author', 'author-password-123')).status, 401)
    const newLogin = await login('author', 'new-author-password-123')
    assert.equal(newLogin.status, 200)
    assert.equal((await request('/rfqs', null, 'GET', newLogin.cookie)).status, 200)
    const loggedOut = await fetch(`http://localhost:${port}/api/auth/logout`, { method: 'POST', headers: { Cookie: newLogin.cookie, 'x-opro-request': '1' } })
    assert.equal(loggedOut.status, 204)
    assert.equal((await request('/rfqs', null, 'GET', newLogin.cookie)).status, 401)
    assert.equal((await request(`/users/${first.data.id}`, null, 'DELETE')).status, 204)
    assert.equal((await request(`/users/${second.data.id}`, null, 'DELETE')).status, 204)
    assert.equal((await request(`/users/${unlinked.data.id}`, null, 'DELETE')).status, 204)
    assert.equal((await request(`/roles/${role.data.id}`, null, 'DELETE')).status, 204)
  })
  await t.test('create RFQ, reject invalid assignments, assign suppliers', async () => {
    const result = await request('/rfqs', { title: 'Regression fixture', lines: [{ name: 'Lamp', qty: 2 }, { name: 'Cable', qty: 3 }] })
    assert.equal(result.status, 201); rfq = result.data
    assert.match(rfq.creationDate, /^\d{4}-\d{2}-\d{2}$/)
    assert.equal((await request('/rfqs', { title: 'Bad date', creationDate: '2026-02-30' })).status, 400)
    assert.equal((await request('/rfqs', { title: '   ' })).status, 400)
    assert.equal((await request(`/rfqs/${rfq.id}`, { id: 'RFQ-CHANGED', title: 'Wrong code' }, 'PUT')).status, 400)
    assert.equal((await request(`/rfqs/${rfq.id}`, { title: '  Renamed procurement RFQ  ' }, 'PUT')).data.title, 'Renamed procurement RFQ')
    assert.equal((await request(`/rfqs/${rfq.id}`, { title: ' ' }, 'PUT')).status, 400)
    assert.equal((await request(`/rfqs/${rfq.id}/assign`, { supplierId: 'SUP-001', type: 'partial', lineIds: [] })).status, 400)
    assert.equal((await request(`/rfqs/${rfq.id}/assign`, { supplierId: 'SUP-001', type: 'partial', lineIds: ['unknown'] })).status, 400)
    for (const supplierId of ['SUP-001', 'SUP-002']) assert.equal((await request(`/rfqs/${rfq.id}/assign`, { supplierId })).status, 200)
    assert.equal((await request(`/rfqs/${rfq.id}`, null, 'GET')).data.status, 'Draft')
    assert.deepEqual((await request('/rfqs', null, 'GET')).data.find((item) => item.id === rfq.id).assignments.map((assignment) => assignment.supplierId), ['SUP-001', 'SUP-002'])
    assert.equal((await request(`/rfqs/${rfq.id}/quote`, { supplierId: 'SUP-001', lines: [{ lineId: rfq.lines[0].lineId, rate: 1 }] })).status, 409)
    assert.equal((await request(`/rfqs/${rfq.id}/status`, { status: 'Published' })).status, 200)
    assert.equal((await request(`/rfqs/${rfq.id}/assign`, { supplierId: 'SUP-001' })).status, 409)
    assert.equal((await request(`/rfqs/${rfq.id}`, null, 'GET')).data.assignments.filter((item) => item.supplierId === 'SUP-001').length, 1)
  })
  await t.test('supplier creators issue portal logins and response editors quote individual items', async () => {
    const role = await request('/roles', { label: 'Supplier intake', permissions: ['workspace.view', 'supplier.create', 'supplier.response.edit'] })
    assert.equal(role.status, 201)
    const user = await request('/users', { roleId: role.data.id, username: 'intake', password: 'intake-password-123' })
    assert.equal(user.status, 201)
    const cookie = (await login('intake', 'intake-password-123')).cookie
    const asIntake = (path, body, method = 'POST') => request(path, body, method, cookie)
    const supplier = await asIntake('/suppliers', { name: 'Single item vendor' })
    assert.equal(supplier.status, 201)
    assert.equal((await asIntake(`/suppliers/${supplier.data.id}`, { notes: 'denied' }, 'PUT')).status, 403)
    const credentials = await asIntake(`/suppliers/${supplier.data.id}/credentials`)
    assert.equal(credentials.status, 201)
    assert.ok(credentials.data.username.startsWith('supplier.'))
    assert.ok(credentials.data.password.length >= 12)
    const supplierCookie = (await login(credentials.data.username, credentials.data.password)).cookie
    const mini = (await request('/rfqs', { title: 'Partial response fixture', lines: [{ name: 'First item', qty: 1, oproStock: 7 }, { name: 'Second item', qty: 2, oproStock: 3 }] })).data
    assert.equal(mini.lines[0].oproStock, 7)
    assert.equal((await request(`/rfqs/${mini.id}`, { lines: [{ ...mini.lines[0], oproStock: -1 }, mini.lines[1]] }, 'PUT')).status, 400)
    assert.equal((await request(`/rfqs/${mini.id}`, { lines: [{ ...mini.lines[0], oproStock: 1.5 }, mini.lines[1]] }, 'PUT')).status, 400)
    assert.ok((await asIntake('/rfqs', null, 'GET')).data.some((item) => item.id === mini.id))
    assert.equal((await request(`/rfqs/${mini.id}/assign`, { supplierId: supplier.data.id, type: 'partial', lineIds: [mini.lines[0].lineId] })).status, 200)
    assert.ok(!(await request('/rfqs', null, 'GET', supplierCookie)).data.some((item) => item.id === mini.id))
    assert.equal((await request(`/rfqs/${mini.id}`, null, 'GET', supplierCookie)).status, 403)
    assert.equal((await request(`/export/rfq-items/${mini.id}`, null, 'GET', supplierCookie)).status, 403)
    const attachmentForm = new FormData()
    attachmentForm.append('file', new Blob(['RFQ drawing notes'], { type: 'text/plain' }), 'drawing-notes.txt')
    const attachmentResponse = await fetch(`http://localhost:${port}/api/rfqs/${mini.id}/attachments`, { method: 'POST', headers: { Cookie: adminCookie, 'x-opro-request': '1' }, body: attachmentForm })
    assert.equal(attachmentResponse.status, 201)
    const attachment = await attachmentResponse.json()
    assert.ok(attachment.id)
    assert.ok(!JSON.stringify(attachment).includes('RFQ drawing notes'))
    assert.equal((await request(`/rfqs/${mini.id}`, null, 'GET')).data.attachments[0].name, 'drawing-notes.txt')
    assert.equal((await fetch(`http://localhost:${port}/api/rfqs/${mini.id}/attachments/${attachment.id}`, { headers: { Cookie: supplierCookie } })).status, 403)
    assert.equal((await request(`/rfqs/${mini.id}/status`, { status: 'Published' })).status, 200)
    assert.ok((await request('/rfqs', null, 'GET', supplierCookie)).data.some((item) => item.id === mini.id))
    const portalView = await request(`/rfqs/${mini.id}`, null, 'GET', supplierCookie)
    assert.equal(portalView.status, 200)
    assert.deepEqual(portalView.data.lines.map((line) => line.lineId), [mini.lines[0].lineId])
    assert.equal(portalView.data.lines[0].oproStock, undefined)
    assert.equal((await request(`/rfqs/${mini.id}`, null, 'GET')).data.lines[0].oproStock, 7)
    const supplierSheet = await fetch(`http://localhost:${port}/api/export/rfq-items/${mini.id}`, { headers: { Cookie: supplierCookie } })
    assert.equal(supplierSheet.status, 200)
    const supplierRows = XLSX.utils.sheet_to_json(XLSX.read(await supplierSheet.arrayBuffer()).Sheets['RFQ Items'])
    assert.equal(supplierRows.length, 1)
    assert.ok(!Object.keys(supplierRows[0]).some((key) => /stock/i.test(key)))
    assert.equal(portalView.data.creationDate, mini.creationDate)
    assert.equal(portalView.data.attachments[0].name, 'drawing-notes.txt')
    const attachmentDownload = await fetch(`http://localhost:${port}/api/rfqs/${mini.id}/attachments/${attachment.id}`, { headers: { Cookie: supplierCookie } })
    assert.equal(attachmentDownload.status, 200)
    assert.equal(await attachmentDownload.text(), 'RFQ drawing notes')
    const imageForm = new FormData()
    imageForm.append('file', new Blob([Buffer.from('fake-image')], { type: 'image/png' }), 'product.png')
    const imageUpload = await fetch(`http://localhost:${port}/api/rfqs/${mini.id}/item-images/${mini.lines[0].lineId}?supplierId=${supplier.data.id}`, { method: 'POST', headers: { Cookie: supplierCookie, 'x-opro-request': '1' }, body: imageForm })
    assert.equal(imageUpload.status, 201)
    const imageView = (await request(`/rfqs/${mini.id}`, null, 'GET', supplierCookie)).data.itemImages
    assert.equal(imageView[0].name, 'product.png')
    assert.equal(imageView[0].lineId, mini.lines[0].lineId)
    assert.ok(!JSON.stringify(imageView).includes('fake-image'))
    assert.equal((await fetch(`http://localhost:${port}/api/rfqs/${mini.id}/item-images/${mini.lines[0].lineId}/${supplier.data.id}`, { headers: { Cookie: supplierCookie } })).status, 200)
    const wholeFileForm = new FormData()
    wholeFileForm.append('file', new Blob(['whole-response-attachment'], { type: 'text/plain' }), 'supplier-terms.txt')
    const wholeFileUpload = await fetch(`http://localhost:${port}/api/rfqs/${mini.id}/quote-attachments?supplierId=${supplier.data.id}`, { method: 'POST', headers: { Cookie: supplierCookie, 'x-opro-request': '1' }, body: wholeFileForm })
    assert.equal(wholeFileUpload.status, 201)
    const wholeFile = await wholeFileUpload.json()
    const itemFileForm = new FormData()
    itemFileForm.append('file', new Blob(['item-brochure'], { type: 'text/plain' }), 'item-brochure.txt')
    const itemFileUpload = await fetch(`http://localhost:${port}/api/rfqs/${mini.id}/item-attachments/${mini.lines[0].lineId}?supplierId=${supplier.data.id}`, { method: 'POST', headers: { Cookie: supplierCookie, 'x-opro-request': '1' }, body: itemFileForm })
    assert.equal(itemFileUpload.status, 201)
    const itemFile = await itemFileUpload.json()
    const supplierFilesView = (await request(`/rfqs/${mini.id}`, null, 'GET', supplierCookie)).data
    assert.equal(supplierFilesView.supplierAttachments[0].name, 'supplier-terms.txt')
    assert.equal(supplierFilesView.itemAttachments[0].lineId, mini.lines[0].lineId)
    assert.ok(!JSON.stringify(supplierFilesView).includes('whole-response-attachment'))
    assert.equal(await (await fetch(`http://localhost:${port}/api/rfqs/${mini.id}/quote-attachments/${wholeFile.id}`, { headers: { Cookie: supplierCookie } })).text(), 'whole-response-attachment')
    assert.equal(await (await fetch(`http://localhost:${port}/api/rfqs/${mini.id}/item-attachments/${mini.lines[0].lineId}/${itemFile.id}`, { headers: { Cookie: supplierCookie } })).text(), 'item-brochure')
    const otherSupplierCookie = (await login('supplier01', 'supplier-password-123')).cookie
    assert.equal((await fetch(`http://localhost:${port}/api/rfqs/${mini.id}/quote-attachments/${wholeFile.id}`, { headers: { Cookie: otherSupplierCookie } })).status, 403)
    const otherItemFile = new FormData()
    otherItemFile.append('file', new Blob(['not assigned'], { type: 'text/plain' }), 'other-item.txt')
    assert.equal((await fetch(`http://localhost:${port}/api/rfqs/${mini.id}/item-attachments/${mini.lines[1].lineId}?supplierId=${supplier.data.id}`, { method: 'POST', headers: { Cookie: supplierCookie, 'x-opro-request': '1' }, body: otherItemFile })).status, 403)
    const forbiddenImage = new FormData()
    forbiddenImage.append('file', new Blob(['fake-image'], { type: 'image/png' }), 'other.png')
    assert.equal((await fetch(`http://localhost:${port}/api/rfqs/${mini.id}/item-images/${mini.lines[1].lineId}?supplierId=${supplier.data.id}`, { method: 'POST', headers: { Cookie: supplierCookie, 'x-opro-request': '1' }, body: forbiddenImage })).status, 403)
    assert.equal((await request(`/rfqs/${rfq.id}`, null, 'GET', supplierCookie)).status, 403)
    assert.equal((await request(`/rfqs/${mini.id}/quote`, { supplierId: 'SUP-001', lines: [{ lineId: mini.lines[0].lineId, rate: 7 }] }, 'POST', supplierCookie)).status, 403)
    assert.equal((await request(`/rfqs/${mini.id}/quote`, { supplierId: supplier.data.id, lines: [{ lineId: mini.lines[1].lineId, rate: 9 }] }, 'POST', supplierCookie)).status, 400)
    assert.equal((await request(`/rfqs/${mini.id}/quote`, { supplierId: supplier.data.id, lines: [{ lineId: mini.lines[0].lineId, rate: 9, offeredName: 'Alternate item', description: 'Supplier item description', brand: 'Acme', model: 'M-42', partNo: 'P-9', leadTime: '4 weeks', eta: '2026-11-15', readyToSendDate: '2026-11-10', paymentTerms: '30 days', warranty: '2 years', remark: 'Packed separately' }] }, 'POST', supplierCookie)).status, 201)
    assert.equal((await request(`/rfqs/${mini.id}`, null, 'GET', supplierCookie)).data.quotes[0].lines[0].readyToSendDate, '2026-11-10')
    assert.equal((await request(`/rfqs/${mini.id}`, null, 'GET', supplierCookie)).data.quotes[0].lines[0].model, 'M-42')
    const savedTerms = (await request(`/rfqs/${mini.id}`, null, 'GET', supplierCookie)).data.quotes[0].lines[0]
    for (const [field, expected] of Object.entries({ offeredName: 'Alternate item', description: 'Supplier item description', leadTime: '4 weeks', paymentTerms: '30 days', warranty: '2 years', remark: 'Packed separately' })) assert.equal(savedTerms[field], expected)
    const stockOnly = await request(`/rfqs/${mini.id}`, { lines: [{ ...mini.lines[0], oproStock: 9 }, mini.lines[1]] }, 'PUT')
    assert.equal(stockOnly.status, 200)
    assert.equal(stockOnly.data.status, 'Responses Received')
    assert.equal(stockOnly.data.lines[0].oproStock, 9)
    assert.equal((await request(`/rfqs/${mini.id}`, null, 'GET', supplierCookie)).data.lines[0].oproStock, undefined)
    assert.equal((await request(`/rfqs/${mini.id}`, null, 'GET')).data.quotes[0].lines[0].rate, 9)
    assert.equal((await request(`/rfqs/${mini.id}/quote`, { supplierId: supplier.data.id, lines: [{ lineId: mini.lines[0].lineId, rate: 9, readyToSendDate: '2026-02-30' }] }, 'POST', supplierCookie)).status, 400)
    assert.equal((await asIntake(`/rfqs/${mini.id}/quote`, { supplierId: supplier.data.id, lines: [{ lineId: mini.lines[0].lineId, rate: 5 }] })).status, 200)
    assert.equal((await asIntake(`/rfqs/${mini.id}/quote`, { supplierId: supplier.data.id, lines: [{ lineId: mini.lines[1].lineId, rate: 5 }] })).status, 400)
    const merged = (await request(`/rfqs/${mini.id}`, null, 'GET')).data.quotes.find((q) => q.supplierId === supplier.data.id)
    assert.equal(merged.lines.length, 1)
    assert.equal((await asIntake(`/rfqs/${mini.id}/quotes/${supplier.data.id}`, { lines: [{ lineId: mini.lines[0].lineId, rate: 6 }] }, 'PUT')).status, 200)
    assert.equal((await asIntake(`/rfqs/${mini.id}/quotes/${supplier.data.id}`, { lines: [{ lineId: mini.lines[1].lineId, rate: 6 }] }, 'PUT')).status, 400)
    assert.equal((await asIntake(`/rfqs/${mini.id}/quote`, { supplierId: supplier.data.id, replaceLines: true, lines: [{ lineId: mini.lines[0].lineId, rate: 12 }] })).status, 200)
    assert.deepEqual((await request(`/rfqs/${mini.id}`, null, 'GET')).data.quotes.find((q) => q.supplierId === supplier.data.id).lines.map((line) => line.lineId), [mini.lines[0].lineId])
    assert.equal((await asIntake(`/rfqs/${mini.id}/quote`, { supplierId: supplier.data.id, replaceLines: true, lines: [] })).status, 200)
    assert.ok(!(await request(`/rfqs/${mini.id}`, null, 'GET')).data.quotes.some((q) => q.supplierId === supplier.data.id))
    const form = new FormData()
    form.append('file', new Blob(['First item,1,10\n'], { type: 'text/plain' }), 'supplier-response.txt')
    const uploaded = await fetch(`http://localhost:${port}/api/rfqs/${mini.id}/quote-upload-queue?supplierId=${supplier.data.id}`, {
      method: 'POST', headers: { Cookie: supplierCookie, 'x-opro-request': '1' }, body: form,
    })
    assert.equal(uploaded.status, 202)
    const queued = await uploaded.json()
    assert.equal(queued.status, 'queued')
    let job
    for (let i = 0; i < 40; i++) {
      const view = (await request(`/rfqs/${mini.id}`, null, 'GET', supplierCookie)).data
      job = view.quoteJobs.find((entry) => entry.id === queued.id)
      assert.ok(job && !JSON.stringify(job).includes('localPath'))
      if (['completed', 'failed'].includes(job.status)) break
      await new Promise((resolve) => setTimeout(resolve, 50))
    }
    assert.equal(job.status, 'completed', job.error)
    assert.equal(job.result.total, 1)
    assert.equal((await request(`/rfqs/${mini.id}/quote-jobs/${job.id}/retry`, { supplierId: supplier.data.id }, 'POST', supplierCookie)).status, 409)
    assert.equal((await request('/rfqs', null, 'GET')).data.find((r) => r.id === mini.id).quoteCount, 0)
    const quoteWorkbook = XLSX.utils.book_new()
    XLSX.utils.book_append_sheet(quoteWorkbook, XLSX.utils.aoa_to_sheet([['Item Name', 'Quantity', 'Unit', 'Brand', 'Model No.', 'Part No.', 'Unit Price (USD)', 'Amount'], ['First item', 1, 'PCS', 'BestCo', 'Q-1', 'P-1', 42.5, 42.5]]), 'Quotation')
    const pricedForm = new FormData()
    pricedForm.append('file', new Blob([XLSX.write(quoteWorkbook, { type: 'buffer', bookType: 'xlsx' })], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }), 'priced-response.xlsx')
    const pricedUpload = await fetch(`http://localhost:${port}/api/rfqs/${mini.id}/quote-upload-queue?supplierId=${supplier.data.id}`, {
      method: 'POST', headers: { Cookie: supplierCookie, 'x-opro-request': '1' }, body: pricedForm,
    })
    assert.equal(pricedUpload.status, 202)
    const pricedJobId = (await pricedUpload.json()).id
    let pricedView
    for (let i = 0; i < 40; i++) {
      pricedView = (await request(`/rfqs/${mini.id}`, null, 'GET', supplierCookie)).data
      if (['completed', 'failed'].includes(pricedView.quoteJobs.find((entry) => entry.id === pricedJobId)?.status)) break
      await new Promise((resolve) => setTimeout(resolve, 50))
    }
    assert.equal(pricedView.quoteJobs.find((entry) => entry.id === pricedJobId)?.status, 'completed')
    assert.equal(pricedView.quoteJobs.find((entry) => entry.id === pricedJobId)?.result.priced, 1)
    assert.equal(pricedView.quotes[0].lines[0].rate, 42.5)
    assert.equal(pricedView.quotes[0].lines[0].brand, 'BestCo')
    assert.equal(pricedView.quotes[0].lines[0].model, 'Q-1')
    assert.equal(pricedView.quotes[0].lines[0].lineId, mini.lines[0].lineId)
    assert.equal((await request(`/rfqs/${mini.id}`, null, 'GET', supplierCookie)).data.quotes[0].lines[0].rate, 42.5)
    const ownQuoteFile = await fetch(`http://localhost:${port}/api/rfqs/${mini.id}/quote-file/${supplier.data.id}`, { headers: { Cookie: supplierCookie } })
    assert.equal(ownQuoteFile.status, 200)
    assert.ok((await ownQuoteFile.arrayBuffer()).byteLength > 0)
    assert.equal((await fetch(`http://localhost:${port}/api/rfqs/${mini.id}/quote-file/SUP-001`, { headers: { Cookie: supplierCookie } })).status, 403)
    const another = (await asIntake('/suppliers', { name: 'Uninvited vendor' })).data
    assert.equal((await asIntake(`/rfqs/${mini.id}/quote`, { supplierId: another.id, lines: [{ lineId: mini.lines[1].lineId, rate: 11 }] })).status, 400)
    assert.ok(!(await request(`/rfqs/${mini.id}`, null, 'GET')).data.assignments.some((item) => item.supplierId === another.id))
    assert.equal((await request(`/rfqs/${mini.id}/assign`, { supplierId: another.id })).status, 200)
    assert.equal((await asIntake(`/rfqs/${mini.id}/quote`, { supplierId: another.id, lines: [{ lineId: mini.lines[1].lineId, rate: 11 }] })).status, 201)
    const anotherCredentials = await asIntake(`/suppliers/${another.id}/credentials`)
    const anotherCookie = (await login(anotherCredentials.data.username, anotherCredentials.data.password)).cookie
    const anotherView = (await request(`/rfqs/${mini.id}`, null, 'GET', anotherCookie)).data
    assert.deepEqual(anotherView.supplierAttachments, [])
    assert.deepEqual(anotherView.itemAttachments, [])
    assert.equal((await fetch(`http://localhost:${port}/api/rfqs/${mini.id}/quote-attachments/${wholeFile.id}`, { headers: { Cookie: anotherCookie } })).status, 403)
    assert.equal((await fetch(`http://localhost:${port}/api/rfqs/${mini.id}/item-attachments/${mini.lines[0].lineId}/${itemFile.id}`, { headers: { Cookie: anotherCookie } })).status, 403)
    assert.equal((await asIntake(`/rfqs/${mini.id}/quote-upload?supplierId=${another.id}`, {}, 'POST')).status, 403)
    const downloadRfq = (id, cookie) => fetch(`http://localhost:${port}/api/export/rfq-items/${id}`, { headers: { Cookie: cookie } })
    assert.equal((await downloadRfq(rfq.id, supplierCookie)).status, 403)
    assert.equal((await downloadRfq(mini.id, cookie)).status, 200)
    const changedItems = await request(`/rfqs/${mini.id}`, { lines: [mini.lines[0], { name: 'Replacement item', qty: 4, secondaryRequirements: 'Weatherproof', requiredDeliveryDate: '2026-11-15' }] }, 'PUT')
    assert.equal(changedItems.status, 200)
    const downloaded = await downloadRfq(mini.id, supplierCookie)
    assert.equal(downloaded.status, 200)
    assert.match(downloaded.headers.get('content-disposition'), /attachment.*RFQ\.xlsx/)
    const workbook = XLSX.read(Buffer.from(await downloaded.arrayBuffer()), { type: 'buffer' })
    const rows = XLSX.utils.sheet_to_json(workbook.Sheets['RFQ Items'])
    assert.deepEqual(rows.map((row) => row['Item Name']), ['First item'])
    const internalWorkbook = XLSX.read(Buffer.from(await (await downloadRfq(mini.id, cookie)).arrayBuffer()), { type: 'buffer' })
    const internalRows = XLSX.utils.sheet_to_json(internalWorkbook.Sheets['RFQ Items'])
    assert.deepEqual(internalRows.map((row) => row['Item Name']), ['First item', 'Replacement item'])
    assert.equal(internalRows[1]['Secondary Requirements'], 'Weatherproof')
    assert.equal(internalRows[1]['Required Delivery Date'], '2026-11-15')
    const reset = await asIntake(`/suppliers/${supplier.data.id}/credentials`)
    assert.equal(reset.status, 200)
    assert.equal(reset.data.username, credentials.data.username)
    assert.equal((await request(`/rfqs/${mini.id}`, null, 'GET', supplierCookie)).status, 401)
    assert.equal((await login(reset.data.username, reset.data.password)).status, 200)
    const revoked = await request(`/roles/${role.data.id}`, { ...role.data, permissions: ['workspace.view'] }, 'PUT')
    assert.equal(revoked.status, 200)
    assert.equal((await asIntake('/suppliers', { name: 'Denied vendor' })).status, 403)
    assert.equal((await asIntake(`/rfqs/${mini.id}/quote`, { supplierId: supplier.data.id, lines: [{ lineId: mini.lines[0].lineId, rate: 10 }] })).status, 403)
  })
  await t.test('quote upload maps an alternate AC brand and leaves a missing middle item unquoted', async () => {
    const requestLines = [
      { name: 'Daikin split AC 1 ton', brand: 'Daikin', qty: 2 },
      { name: 'Copper cable 2.5 sqmm', qty: 10 },
      { name: 'Office chair', qty: 5 },
      { name: 'Wall lamp', qty: 4 },
    ]
    const created = (await request('/rfqs', { title: 'Alternative brand fixture', lines: requestLines })).data
    assert.equal((await request(`/rfqs/${created.id}/assign`, { supplierId: 'SUP-001' })).status, 200)
    assert.equal((await request(`/rfqs/${created.id}/status`, { status: 'Published' })).status, 200)
    const workbook = XLSX.utils.book_new()
    XLSX.utils.book_append_sheet(workbook, XLSX.utils.aoa_to_sheet([
      ['Item Name', 'Quantity', 'Brand', 'Unit Price (USD)'],
      ['Onida split AC 1 ton', 2, 'Onida', 100],
      ['Copper cable 2.5 sqmm', 10, '', 15],
      ['Wall lamp', 4, '', 8],
    ]), 'Quote')
    const form = new FormData()
    form.append('file', new Blob([XLSX.write(workbook, { type: 'buffer', bookType: 'xlsx' })], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }), 'alternative.xlsx')
    const response = await fetch(`http://localhost:${port}/api/rfqs/${created.id}/quote-upload?supplierId=SUP-001`, { method: 'POST', headers: { Cookie: adminCookie, 'x-opro-request': '1' }, body: form })
    assert.equal(response.status, 201)
    const result = await response.json()
    assert.equal(result.matched, 3)
    assert.deepEqual(result.unmatched, ['Office chair'])
    const lines = (await request(`/rfqs/${created.id}`, null, 'GET')).data.quotes.find((quote) => quote.supplierId === 'SUP-001').lines
    assert.deepEqual(lines.map((line) => line.lineId), [created.lines[0].lineId, created.lines[1].lineId, created.lines[3].lineId])
    assert.equal(lines[0].rate, 100)
    assert.equal(lines[0].brand, 'Onida')
    assert.equal(lines[0].offeredName, 'Onida split AC 1 ton')
    assert.equal(lines[2].rate, 8)
  })
  await t.test('repeat submissions update selected items and canonicalize supplier identity', async () => {
    const body = { supplierId: 'SUP-001', supplierName: 'Wrong name', lines: [{ lineId: rfq.lines[0].lineId, rate: 1 }] }
    assert.equal((await request(`/rfqs/${rfq.id}/quote`, body)).status, 201)
    assert.equal((await request(`/rfqs/${rfq.id}/quote`, body)).status, 200)
    const result = await request(`/rfqs/${rfq.id}`, null, 'GET')
    assert.equal(result.data.quotes.length, 1)
    assert.equal(result.data.quotes[0].supplierName, 'A')
    assert.equal((await request(`/rfqs/${rfq.id}/quote`, { ...body, supplierId: 'SUP-unknown' })).status, 400)
  })
  await t.test('partial revisions change only the selected supplier items', async () => {
    const target = (await request('/rfqs', { title: 'Quote revisions', lines: [{ name: 'Valve', qty: 2 }, { name: 'Pump', qty: 1 }] })).data
    assert.equal((await request(`/rfqs/${target.id}/assign`, { supplierId: 'SUP-001' })).status, 200)
    assert.equal((await request(`/rfqs/${target.id}/status`, { status: 'Published' })).status, 200)
    const quote = (lines) => request(`/rfqs/${target.id}/quote`, { supplierId: 'SUP-001', lines })
    assert.equal((await quote([{ lineId: target.lines[0].lineId, rate: 10 }, { lineId: target.lines[1].lineId, rate: 40 }])).status, 201)
    assert.equal((await quote([{ lineId: target.lines[0].lineId, rate: 12 }])).status, 200)
    const revised = (await request(`/rfqs/${target.id}`, null, 'GET')).data.quotes[0]
    assert.deepEqual(Object.fromEntries(revised.lines.map((line) => [line.lineId, line.rate])), { [target.lines[0].lineId]: 12, [target.lines[1].lineId]: 40 })
    assert.ok(revised.lineRevisions[target.lines[0].lineId])
    assert.equal((await quote([{ lineId: target.lines[1].lineId, rate: 0 }])).status, 200)
    const cleared = (await request(`/rfqs/${target.id}`, null, 'GET')).data.quotes[0]
    assert.deepEqual(cleared.lines.map((line) => line.lineId), [target.lines[0].lineId])
    assert.ok(cleared.lineRevisions[target.lines[1].lineId])
  })
  await t.test('award rejects incomplete cheap bids and missing split items', async () => {
    assert.equal((await request(`/rfqs/${rfq.id}/award`, { supplierId: 'SUP-001', amount: 0 })).status, 400)
  })
  await t.test('blank RFQ rows are skipped and partial split awards reopen on item edits', async () => {
    const made = await request('/rfqs', { title: 'Blank row fixture', creationDate: '2026-01-15', lines: [{ name: '', qty: 1 }, { name: '  ', qty: 1, description: '' }, { name: 'Lamp', qty: 2 }, { name: 'Unquoted cable', qty: 3 }] })
    assert.equal(made.status, 201)
    const partial = made.data
    assert.equal(partial.creationDate, '2026-01-15')
    assert.deepEqual(partial.lines.map((line) => line.name), ['Lamp', 'Unquoted cable'])
    assert.equal((await request(`/rfqs/${partial.id}/assign`, { supplierId: 'SUP-001' })).status, 200)
    assert.equal((await request(`/rfqs/${partial.id}/status`, { status: 'Published' })).status, 200)
    assert.equal((await request(`/rfqs/${partial.id}/quote`, { supplierId: 'SUP-001', lines: [{ lineId: partial.lines[0].lineId, rate: 7 }] })).status, 201)
    const awarded = await request(`/rfqs/${partial.id}/award`, { type: 'split', awards: [{ supplierId: 'SUP-001', lineIds: [partial.lines[0].lineId] }] })
    assert.equal(awarded.status, 200)
    assert.equal(awarded.data.award.amount, 14)
    assert.deepEqual(awarded.data.award.unawardedLineIds, [partial.lines[1].lineId])
    assert.ok(!(await request('/reports', null, 'GET')).data.savingsByRfq.some((row) => row.id === partial.id))
    assert.equal((await request(`/rfqs/${partial.id}/delivery`, { supplierId: 'SUP-001', deliver: true })).data.status, 'Awarded')
    const correctedDate = await request(`/rfqs/${partial.id}`, { creationDate: '2026-01-16', createdAt: 1 }, 'PUT')
    assert.equal(correctedDate.data.status, 'Awarded')
    assert.equal(correctedDate.data.creationDate, '2026-01-16')
    assert.equal(correctedDate.data.createdAt, partial.createdAt)
    assert.equal((await request(`/rfqs/${partial.id}`, { creationDate: '2026-02-30' }, 'PUT')).status, 400)
    const unchanged = await request(`/rfqs/${partial.id}`, { lines: partial.lines }, 'PUT')
    assert.equal(unchanged.data.status, 'Awarded')
    const reopened = await request(`/rfqs/${partial.id}`, { lines: [{ ...partial.lines[0], qty: 4 }, { name: '', qty: 1 }, partial.lines[1], { name: 'New item', qty: 1 }] }, 'PUT')
    assert.equal(reopened.status, 200)
    assert.equal(reopened.data.status, 'Evaluation')
    assert.equal(reopened.data.award, null)
    assert.equal(reopened.data.awardHistory.length, 1)
    assert.equal(reopened.data.awardHistory[0].deliveries[0].status, 'delivered')
    assert.equal(reopened.data.lines.length, 3)
    assert.equal(reopened.data.assignments[0].lineIds.length, 3)
    assert.equal((await request(`/rfqs/${partial.id}`, { lines: [reopened.data.lines[0], { name: '', qty: 1 }, reopened.data.lines[2]] }, 'PUT')).status, 200)
    const afterRemoval = (await request(`/rfqs/${partial.id}`, null, 'GET')).data
    assert.deepEqual(afterRemoval.lines.map((line) => line.name), ['Lamp', 'New item'])
    assert.equal(afterRemoval.quotes[0].lines[0].qty, 4)
    assert.equal(afterRemoval.awardHistory.length, 1)
    const removedQuotedItem = await request(`/rfqs/${partial.id}`, { lines: [afterRemoval.lines[1]] }, 'PUT')
    assert.equal(removedQuotedItem.status, 200)
    assert.deepEqual((await request(`/rfqs/${partial.id}`, null, 'GET')).data.quotes[0].lines, [])
  })
  await t.test('comparison can add a missing quote line, rejects invalid values', async () => {
    assert.equal((await request(`/rfqs/${rfq.id}/quotes/SUP-001`, { lines: [{ lineId: rfq.lines[1].lineId, rate: 10, readyToSendDate: '2026-11-10' }] }, 'PUT')).status, 200)
    assert.equal((await request(`/rfqs/${rfq.id}/quotes/SUP-001`, { lines: [{ lineId: rfq.lines[1].lineId, rate: -1 }] }, 'PUT')).status, 400)
    assert.equal((await request(`/rfqs/${rfq.id}/quotes/SUP-001`, { lines: [{ lineId: rfq.lines[1].lineId, readyToSendDate: '2026-02-30' }] }, 'PUT')).status, 400)
    const result = await request(`/rfqs/${rfq.id}`, null, 'GET')
    assert.equal(result.data.quotes[0].lines.length, 2)
    assert.equal(result.data.quotes[0].lines.find((line) => line.lineId === rfq.lines[1].lineId).readyToSendDate, '2026-11-10')
  })
  await t.test('full assignments include newly added RFQ items', async () => {
    const result = await request(`/rfqs/${rfq.id}`, { lines: [...rfq.lines, { name: 'Extra', qty: 1 }] }, 'PUT')
    assert.equal(result.status, 200)
    assert.equal(result.data.assignments[0].lineIds.length, 3)
    assert.equal((await request(`/rfqs/${rfq.id}`, { lines: rfq.lines }, 'PUT')).status, 200)
  })
  await t.test('award totals are computed on server and finalization is immutable', async () => {
    const result = await request(`/rfqs/${rfq.id}/award`, { supplierId: 'SUP-001', amount: 0.01 })
    assert.equal(result.status, 200)
    assert.equal(result.data.award.amount, 32)
    const renamed = await request(`/rfqs/${rfq.id}`, { title: 'Final award review' }, 'PUT')
    assert.equal(renamed.status, 200)
    assert.equal(renamed.data.id, rfq.id)
    assert.equal(renamed.data.title, 'Final award review')
    assert.equal(renamed.data.award.amount, 32)
    assert.equal(renamed.data.status, 'Awarded')
    assert.equal((await request(`/rfqs/${rfq.id}/award`, { type: 'reject' })).status, 400)
    assert.equal((await request(`/rfqs/${rfq.id}/quotes/SUP-001`, { lines: [{ lineId: rfq.lines[0].lineId, rate: 999 }] }, 'PUT')).status, 409)
    assert.equal((await request(`/rfqs/${rfq.id}/status`, { status: 'Draft' })).status, 409)
  })
  await t.test('recommendation validates weights and fails visibly without AI', async () => {
    assert.equal((await request('/rfqs/RFQ-2026-0042/recommend', { weights: { price: 0, quality: 0, delivery: 0 } })).status, 400)
    assert.equal((await request('/rfqs/RFQ-2026-0042/recommend', { weights: { price: 100, quality: 0, delivery: 0 } })).status, 503)
  })
  await t.test('notifications target approvers and preserve each account’s unread state', async () => {
    const approverRole = (await request('/roles', { label: 'Notification approvers', permissions: ['workspace.view', 'approve.hod'] })).data
    const buyerRole = (await request('/roles', { label: 'Notification buyers', permissions: ['workspace.view', 'rfq.create'] })).data
    const first = (await request('/users', { roleId: approverRole.id, username: 'approver-one', password: 'approver-one-password-123' })).data
    const second = (await request('/users', { roleId: approverRole.id, username: 'approver-two', password: 'approver-two-password-123' })).data
    const buyer = (await request('/users', { roleId: buyerRole.id, username: 'notice-buyer', password: 'notice-buyer-password-123' })).data
    const firstCookie = (await login(first.username, 'approver-one-password-123')).cookie
    const secondCookie = (await login(second.username, 'approver-two-password-123')).cookie
    const buyerCookie = (await login(buyer.username, 'notice-buyer-password-123')).cookie
    const target = (await request('/rfqs', { title: 'Notification fixture', lines: [{ name: 'Lamp', qty: 1 }] })).data
    assert.equal((await request(`/rfqs/${target.id}/assign`, { supplierId: 'SUP-001' })).status, 200)
    assert.equal((await request(`/rfqs/${target.id}/status`, { status: 'Published' })).status, 200)
    assert.equal((await request(`/rfqs/${target.id}/quote`, { supplierId: 'SUP-001', lines: [{ lineId: target.lines[0].lineId, rate: 10 }] })).status, 201)
    assert.equal((await request(`/rfqs/${target.id}/forward-evaluation`)).status, 200)
    const firstNotices = (await request('/notifications', null, 'GET', firstCookie)).data
    const requestNotice = firstNotices.find((notice) => notice.rfqId === target.id && notice.type === 'approval_request')
    assert.ok(requestNotice?.unread)
    assert.match(requestNotice.title, /HOD approval needed/)
    assert.ok(!firstNotices.some((notice) => notice.rfqId === target.id && /Finance approval needed/.test(notice.title)))
    assert.ok(!(await request('/notifications', null, 'GET', buyerCookie)).data.some((notice) => notice.type === 'approval_request' && notice.rfqId === target.id))
    assert.ok((await request('/notifications', null, 'GET', buyerCookie)).data.some((notice) => notice.type === 'response' && notice.rfqId === target.id))
    assert.equal((await request(`/notifications/${requestNotice.id}/read`, {}, 'POST', buyerCookie)).status, 404)
    assert.equal((await request(`/notifications/${requestNotice.id}/read`, {}, 'POST', firstCookie)).data.unread, false)
    assert.equal((await request('/notifications', null, 'GET', secondCookie)).data.find((notice) => notice.id === requestNotice.id).unread, true)
    assert.equal((await request('/notifications/read-all', {}, 'POST', firstCookie)).status, 200)
    assert.equal((await request('/notifications', null, 'GET', secondCookie)).data.find((notice) => notice.id === requestNotice.id).unread, true)
    assert.equal((await request(`/rfqs/${target.id}/clarifications`, { from: 'Supplier A', supplierId: 'SUP-001', message: 'Can you clarify delivery?' })).status, 201)
    assert.ok((await request('/notifications', null, 'GET', buyerCookie)).data.some((notice) => notice.type === 'clarification' && notice.rfqId === target.id))
    assert.equal((await request(`/rfqs/${target.id}/approve`, { role: 'hod' }, 'POST', firstCookie)).status, 200)
    assert.ok(!(await request('/notifications', null, 'GET', secondCookie)).data.some((notice) => notice.id === requestNotice.id))
    assert.equal((await request(`/rfqs/${target.id}/award`, { supplierId: 'SUP-001' })).status, 200)
    assert.equal((await request(`/rfqs/${target.id}`, { lines: [{ ...target.lines[0], qty: 2 }] }, 'PUT')).data.status, 'Evaluation')
    const reopenedRequests = (await request('/notifications', null, 'GET', secondCookie)).data.filter((notice) => notice.type === 'approval_request' && notice.rfqId === target.id)
    assert.equal(reopenedRequests.length, 1)
    assert.notEqual(reopenedRequests[0].id, requestNotice.id)
  })
  await t.test('diagnostics correlate failed requests and record sanitized UI events', async () => {
    const failed = await request(`/rfqs/${rfq.id}/award`, { supplierId: 'SUP-001' })
    assert.ok(failed.requestId)
    const logs = await request(`/logs?q=${failed.requestId}`, null, 'GET')
    assert.equal(logs.data.entries.length, 1)
    assert.equal(logs.data.entries[0].status, failed.status)
    assert.equal(logs.data.entries[0].level, 'warn')
    assert.equal((await request('/logs/events', { events: [{ event: 'ui.click', message: 'Save password=secret', path: '/award' }] })).data.recorded, 1)
    const clicks = await request('/logs?q=ui.click', null, 'GET')
    assert.ok(!JSON.stringify(clicks.data.entries).includes('secret'))
    assert.equal(clicks.data.policy.maxEntries, 20000)
    assert.equal((await request('/logs/events', { events: Array(26).fill({ event: 'ui.click' }) })).status, 400)
  })
})
