import test from 'node:test'
import assert from 'node:assert/strict'
import { spawn } from 'node:child_process'
import { mkdtemp, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { once } from 'node:events'
import { hashPassword } from '../server/lib/auth.js'

test('procurement API regression checks on isolated data', async (t) => {
  const data = await mkdtemp(join(tmpdir(), 'opro-regression-'))
  const port = 44123
  const adminPassword = 'test-only-admin-password-123'
  const server = spawn(process.execPath, ['server/index.js'], { env: { ...process.env, PORT: String(port), RFQ_DATA_DIR: data, OPENAI_API_KEY: '', ADMIN_BOOTSTRAP_USERNAME: 'admin', ADMIN_BOOTSTRAP_PASSWORD_HASH: await hashPassword(adminPassword), ACCOUNT_PASSWORD_ENCRYPTION_KEY: Buffer.alloc(32, 7).toString('base64url') }, stdio: ['ignore', 'pipe', 'pipe'] })
  let output = ''
  server.stdout.on('data', (x) => { output += x })
  server.stderr.on('data', (x) => { output += x })
  t.after(async () => { const exited = once(server, 'exit'); server.kill(); await exited; await rm(data, { recursive: true, force: true }) })
  let adminCookie = ''
  const request = async (path, body, method = 'POST', cookie = adminCookie, extraHeaders = {}) => {
    const res = await fetch(`http://localhost:${port}/api${path}`, { method, headers: { 'Content-Type': 'application/json', 'x-opro-request': '1', ...(cookie ? { Cookie: cookie } : {}), ...extraHeaders }, ...(method === 'GET' ? {} : { body: JSON.stringify(body || {}) }) })
    return { status: res.status, data: res.status === 204 ? null : await res.json(), requestId: res.headers.get('x-request-id') }
  }
  for (let i = 0; i < 100; i++) {
    try { if ((await request('/health', null, 'GET')).status === 200) break } catch {}
    if (server.exitCode != null || i === 99) throw new Error(output || 'API did not start')
    await new Promise((resolve) => setTimeout(resolve, 100))
  }
  const login = async (username, password) => {
    const res = await fetch(`http://localhost:${port}/api/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json', 'x-opro-request': '1' }, body: JSON.stringify({ username, password }) })
    return { status: res.status, data: await res.json(), cookie: res.headers.get('set-cookie')?.split(';')[0] || '' }
  }
  assert.equal((await request('/roles', null, 'GET', '')).status, 401)
  assert.equal((await request('/roles', null, 'GET', '', { 'x-role-key': 'admin' })).status, 401)
  assert.equal((await login('admin', 'wrong-password')).status, 401)
  const signedIn = await login('admin', adminPassword)
  assert.equal(signedIn.status, 200)
  adminCookie = signedIn.cookie
  assert.ok(adminCookie.startsWith('opro_session='))
  assert.equal((await request('/auth/me', null, 'GET')).data.account.username, 'admin')
  assert.equal((await request('/roles', {}, 'POST', adminCookie, { 'x-opro-request': '0' })).status, 403)
  let rfq
  await t.test('catalogue fields, full-catalogue search, pagination and metadata', async () => {
    const fields = { name: 'Catalogue source fixture', aiName: 'AI-UNIQUE-LOOKUP', description: 'Full description', sku: '00042', category: 'Custom category', subcategory: 'Custom subcategory', uom: '', partNo: 'MPN-UNIQUE-LOOKUP', unitName: 'Source unit' }
    const added = await request('/items', fields)
    assert.equal(added.status, 201)
    for (const [key, value] of Object.entries(fields)) assert.equal(added.data.item[key], value)
    const search = await request('/items?paged=true&q=AI-UNIQUE-LOOKUP', null, 'GET')
    assert.equal(search.data.total, 1)
    assert.equal(search.data.items[0].sku, '00042')
    assert.equal((await request('/items?paged=true&q=MPN-UNIQUE-LOOKUP&offset=1', null, 'GET')).data.items.length, 0)
    const meta = await request('/items/meta', null, 'GET')
    assert.ok(meta.data.categories.includes('Custom category'))
    assert.ok(meta.data.subcategories.includes('Custom subcategory'))
    await request(`/items/${added.data.item.id}`, { aiName: 'Edited AI', subcategory: 'Edited subcategory', unitName: '' }, 'PUT')
    const edited = await request('/items?paged=true&q=Edited%20AI', null, 'GET')
    assert.equal(edited.data.items[0].unitName, '')
    assert.equal(edited.data.items[0].subcategory, 'Edited subcategory')
  })
  await t.test('roles share permissions while users keep individual credentials', async () => {
    const cookies = new Map()
    const asUser = (path, user, body, method = body ? 'POST' : 'GET') => request(path, body, method, cookies.get(user) || '', { 'x-role-key': user, 'x-supplier-id': 'SUP-002' })
    assert.equal((await request('/roles', null, 'GET')).data.length, 1)
    assert.equal((await request('/users', null, 'GET')).data.length, 1)
    const role = await request('/roles', { label: 'Restricted Reviewer #1', permissions: ['workspace.view', 'rfq.evaluate'] })
    assert.equal(role.status, 201)
    assert.ok(!('username' in role.data) && !('passwordHash' in role.data))
    const first = await request('/users', { roleId: role.data.id, username: 'reviewer', password: 'reviewer-password-123', readOnly: true })
    assert.equal(first.status, 201)
    const second = await request('/users', { roleId: role.data.id, username: '  Second Reviewer #2  ', password: 'reviewer2-password-123' })
    assert.equal(second.status, 201)
    assert.equal(second.data.username, 'second reviewer #2')
    assert.equal((await login('SECOND REVIEWER #2', 'reviewer2-password-123')).status, 200)
    assert.equal((await request('/roles', null, 'GET')).data.length, 2)
    assert.equal((await request('/users', null, 'GET')).data.length, 3)
    assert.equal((await request(`/users/${first.data.id}/password`, null, 'GET', '')).status, 401)
    for (let attempt = 0; attempt < 2; attempt++) {
      const revealed = await request(`/users/${first.data.id}/password`, null, 'GET')
      assert.deepEqual(revealed.data, { username: 'reviewer', password: 'reviewer-password-123' })
    }
    assert.ok(!JSON.stringify((await request('/users', null, 'GET')).data).includes('reviewer-password-123'))
    cookies.set('reviewer', (await login('reviewer', 'reviewer-password-123')).cookie)
    cookies.set('reviewer2', (await login('second reviewer #2', 'reviewer2-password-123')).cookie)
    assert.equal((await asUser(`/users/${first.data.id}/password`, 'reviewer')).status, 403)
    assert.equal((await asUser('/rfqs', 'reviewer')).status, 200)
    assert.equal((await asUser('/rfqs', 'reviewer', { title: 'Denied' })).status, 403)
    assert.equal((await asUser('/reports', 'reviewer')).status, 403)
    assert.equal((await asUser('/reports', 'reviewer2')).status, 403)
    assert.equal((await request(`/roles/${role.data.id}`, { ...role.data, permissions: [...role.data.permissions, 'reports.view'] }, 'PUT')).status, 200)
    assert.equal((await asUser('/reports', 'reviewer')).status, 200)
    assert.equal((await asUser('/reports', 'reviewer2')).status, 200)
    assert.equal((await request(`/roles/${role.data.id}`, role.data, 'PUT')).status, 409)
    assert.equal((await request(`/roles/${role.data.id}`, null, 'DELETE')).status, 409)
    assert.equal((await request('/roles/admin', { label: 'Changed', permissions: [], version: 1 }, 'PUT')).status, 403)
    assert.equal((await asUser('/roles', 'reviewer', { label: 'Escalation', permissions: [] })).status, 403)
    const updatedRole = (await request('/roles', null, 'GET')).data.find((item) => item.id === role.data.id)
    assert.equal((await request(`/roles/${role.data.id}`, { ...updatedRole, enabled: false }, 'PUT')).status, 200)
    assert.equal((await asUser('/rfqs', 'reviewer')).status, 401)
    assert.equal((await asUser('/rfqs', 'reviewer2')).status, 401)
    const supplierRole = await request('/roles', { label: 'Supplier account', permissions: ['portal.access', 'quote.submit'] })
    assert.equal(supplierRole.status, 201)
    assert.equal((await request('/users', { roleId: supplierRole.data.id, username: 'supplier01', password: 'supplier-password-123' })).status, 400)
    const supplier = await request('/users', { roleId: supplierRole.data.id, username: 'supplier01', password: 'supplier-password-123', supplierId: 'SUP-001' })
    assert.equal(supplier.status, 201)
    cookies.set('supplier', (await login('supplier01', 'supplier-password-123')).cookie)
    const own = await asUser('/rfqs/RFQ-2026-0042', 'supplier')
    assert.equal(own.status, 200)
    assert.ok(own.data.quotes.every((q) => q.supplierId === 'SUP-001'))
    assert.equal((await asUser('/rfqs/RFQ-2026-0041', 'supplier')).status, 403)
    assert.equal((await asUser('/rfqs/RFQ-2026-0042/quote', 'supplier', { supplierId: 'SUP-002' })).status, 403)
    const authorRole = await request('/roles', { label: 'Draft Author', permissions: ['workspace.view', 'rfq.create'] })
    const author = await request('/users', { roleId: authorRole.data.id, username: 'author', password: 'author-password-123' })
    cookies.set('author', (await login('author', 'author-password-123')).cookie)
    const draft = await asUser('/rfqs', 'author', { title: 'Draft only', lines: [{ name: 'Lamp', qty: 1 }] })
    assert.equal(draft.status, 201)
    assert.equal((await asUser(`/rfqs/${draft.data.id}/assign`, 'author', { supplierId: 'SUP-001' })).status, 403)
    const reset = await request(`/users/${author.data.id}`, { ...author.data, password: 'new-author-password-123' }, 'PUT')
    assert.equal(reset.status, 200)
    assert.equal((await request(`/users/${author.data.id}/password`, null, 'GET')).data.password, 'new-author-password-123')
    assert.equal((await asUser('/rfqs', 'author')).status, 401)
    assert.equal((await login('author', 'author-password-123')).status, 401)
    const newLogin = await login('author', 'new-author-password-123')
    assert.equal(newLogin.status, 200)
    assert.equal((await request('/rfqs', null, 'GET', newLogin.cookie)).status, 200)
    const loggedOut = await fetch(`http://localhost:${port}/api/auth/logout`, { method: 'POST', headers: { Cookie: newLogin.cookie, 'x-opro-request': '1' } })
    assert.equal(loggedOut.status, 204)
    assert.equal((await request('/rfqs', null, 'GET', newLogin.cookie)).status, 401)
    assert.equal((await request(`/users/${first.data.id}`, null, 'DELETE')).status, 204)
    assert.equal((await request(`/users/${second.data.id}`, null, 'DELETE')).status, 204)
    assert.equal((await request(`/roles/${role.data.id}`, null, 'DELETE')).status, 204)
  })
  await t.test('create RFQ, reject invalid assignments, assign suppliers', async () => {
    const result = await request('/rfqs', { title: 'Regression fixture', lines: [{ name: 'Lamp', qty: 2 }, { name: 'Cable', qty: 3 }] })
    assert.equal(result.status, 201); rfq = result.data
    assert.equal((await request(`/rfqs/${rfq.id}/assign`, { supplierId: 'SUP-001', type: 'partial', lineIds: [] })).status, 400)
    assert.equal((await request(`/rfqs/${rfq.id}/assign`, { supplierId: 'SUP-001', type: 'partial', lineIds: ['unknown'] })).status, 400)
    for (const supplierId of ['SUP-001', 'SUP-002']) assert.equal((await request(`/rfqs/${rfq.id}/assign`, { supplierId })).status, 200)
  })
  await t.test('supplier creators issue portal logins and response editors quote individual items', async () => {
    const role = await request('/roles', { label: 'Supplier intake', permissions: ['workspace.view', 'supplier.create', 'supplier.response.edit'] })
    assert.equal(role.status, 201)
    const user = await request('/users', { roleId: role.data.id, username: 'intake', password: 'intake-password-123' })
    assert.equal(user.status, 201)
    const cookie = (await login('intake', 'intake-password-123')).cookie
    const asIntake = (path, body, method = 'POST') => request(path, body, method, cookie)
    const supplier = await asIntake('/suppliers', { name: 'Single item vendor' })
    assert.equal(supplier.status, 201)
    assert.equal((await asIntake(`/suppliers/${supplier.data.id}`, { notes: 'denied' }, 'PUT')).status, 403)
    const credentials = await asIntake(`/suppliers/${supplier.data.id}/credentials`)
    assert.equal(credentials.status, 201)
    assert.ok(credentials.data.username.startsWith('supplier.'))
    assert.ok(credentials.data.password.length >= 12)
    const supplierCookie = (await login(credentials.data.username, credentials.data.password)).cookie
    const mini = (await request('/rfqs', { title: 'Partial response fixture', lines: [{ name: 'First item', qty: 1 }, { name: 'Second item', qty: 2 }] })).data
    assert.ok((await asIntake('/rfqs', null, 'GET')).data.some((item) => item.id === mini.id))
    assert.equal((await request(`/rfqs/${mini.id}/assign`, { supplierId: supplier.data.id, type: 'partial', lineIds: [mini.lines[0].lineId] })).status, 200)
    const portalView = await request(`/rfqs/${mini.id}`, null, 'GET', supplierCookie)
    assert.equal(portalView.status, 200)
    assert.equal(portalView.data.lines.length, 2)
    assert.equal((await request(`/rfqs/${rfq.id}`, null, 'GET', supplierCookie)).status, 403)
    assert.equal((await request(`/rfqs/${mini.id}/quote`, { supplierId: 'SUP-001', lines: [{ lineId: mini.lines[0].lineId, rate: 7 }] }, 'POST', supplierCookie)).status, 403)
    assert.equal((await request(`/rfqs/${mini.id}/quote`, { supplierId: supplier.data.id, lines: [{ lineId: mini.lines[1].lineId, rate: 9 }] }, 'POST', supplierCookie)).status, 201)
    assert.equal((await asIntake(`/rfqs/${mini.id}/quote`, { supplierId: supplier.data.id, lines: [{ lineId: mini.lines[0].lineId, rate: 5 }] })).status, 200)
    const merged = (await request(`/rfqs/${mini.id}`, null, 'GET')).data.quotes.find((q) => q.supplierId === supplier.data.id)
    assert.equal(merged.lines.length, 2)
    assert.equal((await asIntake(`/rfqs/${mini.id}/quotes/${supplier.data.id}`, { lines: [{ lineId: mini.lines[0].lineId, rate: 6 }] }, 'PUT')).status, 200)
    assert.equal((await asIntake(`/rfqs/${mini.id}/quote`, { supplierId: supplier.data.id, lines: [{ lineId: mini.lines[1].lineId, rate: 0 }] })).status, 200)
    assert.deepEqual((await request(`/rfqs/${mini.id}`, null, 'GET')).data.quotes.find((q) => q.supplierId === supplier.data.id).lines.map((line) => line.lineId), [mini.lines[0].lineId])
    assert.equal((await asIntake(`/rfqs/${mini.id}/quote`, { supplierId: supplier.data.id, replaceLines: true, lines: [{ lineId: mini.lines[1].lineId, rate: 12 }] })).status, 200)
    assert.deepEqual((await request(`/rfqs/${mini.id}`, null, 'GET')).data.quotes.find((q) => q.supplierId === supplier.data.id).lines.map((line) => line.lineId), [mini.lines[1].lineId])
    assert.equal((await asIntake(`/rfqs/${mini.id}/quote`, { supplierId: supplier.data.id, replaceLines: true, lines: [] })).status, 200)
    assert.ok(!(await request(`/rfqs/${mini.id}`, null, 'GET')).data.quotes.some((q) => q.supplierId === supplier.data.id))
    assert.equal((await request('/rfqs', null, 'GET')).data.find((r) => r.id === mini.id).quoteCount, 0)
    const another = (await asIntake('/suppliers', { name: 'Uninvited vendor' })).data
    assert.equal((await asIntake(`/rfqs/${mini.id}/quote`, { supplierId: another.id, lines: [{ lineId: mini.lines[1].lineId, rate: 11 }] })).status, 400)
    assert.ok(!(await request(`/rfqs/${mini.id}`, null, 'GET')).data.assignments.some((item) => item.supplierId === another.id))
    assert.equal((await request(`/rfqs/${mini.id}/assign`, { supplierId: another.id })).status, 200)
    assert.equal((await asIntake(`/rfqs/${mini.id}/quote`, { supplierId: another.id, lines: [{ lineId: mini.lines[1].lineId, rate: 11 }] })).status, 201)
    assert.equal((await asIntake(`/rfqs/${mini.id}/quote-upload?supplierId=${another.id}`, {}, 'POST')).status, 403)
    const reset = await asIntake(`/suppliers/${supplier.data.id}/credentials`)
    assert.equal(reset.status, 200)
    assert.equal(reset.data.username, credentials.data.username)
    assert.equal((await request(`/rfqs/${mini.id}`, null, 'GET', supplierCookie)).status, 401)
    assert.equal((await login(reset.data.username, reset.data.password)).status, 200)
    const revoked = await request(`/roles/${role.data.id}`, { ...role.data, permissions: ['workspace.view'] }, 'PUT')
    assert.equal(revoked.status, 200)
    assert.equal((await asIntake('/suppliers', { name: 'Denied vendor' })).status, 403)
    assert.equal((await asIntake(`/rfqs/${mini.id}/quote`, { supplierId: supplier.data.id, lines: [{ lineId: mini.lines[0].lineId, rate: 10 }] })).status, 403)
  })
  await t.test('repeat submissions update selected items and canonicalize supplier identity', async () => {
    const body = { supplierId: 'SUP-001', supplierName: 'Wrong name', lines: [{ lineId: rfq.lines[0].lineId, rate: 1 }] }
    assert.equal((await request(`/rfqs/${rfq.id}/quote`, body)).status, 201)
    assert.equal((await request(`/rfqs/${rfq.id}/quote`, body)).status, 200)
    const result = await request(`/rfqs/${rfq.id}`, null, 'GET')
    assert.equal(result.data.quotes.length, 1)
    assert.equal(result.data.quotes[0].supplierName, 'A')
    assert.equal((await request(`/rfqs/${rfq.id}/quote`, { ...body, supplierId: 'SUP-unknown' })).status, 400)
  })
  await t.test('award rejects incomplete cheap bids and missing split items', async () => {
    assert.equal((await request(`/rfqs/${rfq.id}/award`, { supplierId: 'SUP-001', amount: 0 })).status, 400)
  })
  await t.test('blank RFQ rows are skipped and partial split awards reopen on item edits', async () => {
    const made = await request('/rfqs', { title: 'Blank row fixture', lines: [{ name: '', qty: 1 }, { name: '  ', qty: 1, description: '' }, { name: 'Lamp', qty: 2 }, { name: 'Unquoted cable', qty: 3 }] })
    assert.equal(made.status, 201)
    const partial = made.data
    assert.deepEqual(partial.lines.map((line) => line.name), ['Lamp', 'Unquoted cable'])
    assert.equal((await request(`/rfqs/${partial.id}/assign`, { supplierId: 'SUP-001' })).status, 200)
    assert.equal((await request(`/rfqs/${partial.id}/quote`, { supplierId: 'SUP-001', lines: [{ lineId: partial.lines[0].lineId, rate: 7 }] })).status, 201)
    const awarded = await request(`/rfqs/${partial.id}/award`, { type: 'split', awards: [{ supplierId: 'SUP-001', lineIds: [partial.lines[0].lineId] }] })
    assert.equal(awarded.status, 200)
    assert.equal(awarded.data.award.amount, 14)
    assert.deepEqual(awarded.data.award.unawardedLineIds, [partial.lines[1].lineId])
    assert.ok(!(await request('/reports', null, 'GET')).data.savingsByRfq.some((row) => row.id === partial.id))
    assert.equal((await request(`/rfqs/${partial.id}/delivery`, { supplierId: 'SUP-001', deliver: true })).data.status, 'Awarded')
    const unchanged = await request(`/rfqs/${partial.id}`, { lines: partial.lines }, 'PUT')
    assert.equal(unchanged.data.status, 'Awarded')
    const reopened = await request(`/rfqs/${partial.id}`, { lines: [{ ...partial.lines[0], qty: 4 }, { name: '', qty: 1 }, partial.lines[1], { name: 'New item', qty: 1 }] }, 'PUT')
    assert.equal(reopened.status, 200)
    assert.equal(reopened.data.status, 'Evaluation')
    assert.equal(reopened.data.award, null)
    assert.equal(reopened.data.awardHistory.length, 1)
    assert.equal(reopened.data.awardHistory[0].deliveries[0].status, 'delivered')
    assert.equal(reopened.data.lines.length, 3)
    assert.equal(reopened.data.assignments[0].lineIds.length, 3)
    assert.equal((await request(`/rfqs/${partial.id}`, { lines: [reopened.data.lines[0], { name: '', qty: 1 }, reopened.data.lines[2]] }, 'PUT')).status, 200)
    const afterRemoval = (await request(`/rfqs/${partial.id}`, null, 'GET')).data
    assert.deepEqual(afterRemoval.lines.map((line) => line.name), ['Lamp', 'New item'])
    assert.equal(afterRemoval.quotes[0].lines[0].qty, 4)
    assert.equal(afterRemoval.awardHistory.length, 1)
    const removedQuotedItem = await request(`/rfqs/${partial.id}`, { lines: [afterRemoval.lines[1]] }, 'PUT')
    assert.equal(removedQuotedItem.status, 200)
    assert.deepEqual((await request(`/rfqs/${partial.id}`, null, 'GET')).data.quotes[0].lines, [])
  })
  await t.test('comparison can add a missing quote line, rejects invalid values', async () => {
    assert.equal((await request(`/rfqs/${rfq.id}/quotes/SUP-001`, { lines: [{ lineId: rfq.lines[1].lineId, rate: 10 }] }, 'PUT')).status, 200)
    assert.equal((await request(`/rfqs/${rfq.id}/quotes/SUP-001`, { lines: [{ lineId: rfq.lines[1].lineId, rate: -1 }] }, 'PUT')).status, 400)
    const result = await request(`/rfqs/${rfq.id}`, null, 'GET')
    assert.equal(result.data.quotes[0].lines.length, 2)
  })
  await t.test('full assignments include newly added RFQ items', async () => {
    const result = await request(`/rfqs/${rfq.id}`, { lines: [...rfq.lines, { name: 'Extra', qty: 1 }] }, 'PUT')
    assert.equal(result.status, 200)
    assert.equal(result.data.assignments[0].lineIds.length, 3)
    assert.equal((await request(`/rfqs/${rfq.id}`, { lines: rfq.lines }, 'PUT')).status, 200)
  })
  await t.test('award totals are computed on server and finalization is immutable', async () => {
    const result = await request(`/rfqs/${rfq.id}/award`, { supplierId: 'SUP-001', amount: 0.01 })
    assert.equal(result.status, 200)
    assert.equal(result.data.award.amount, 32)
    assert.equal((await request(`/rfqs/${rfq.id}/award`, { type: 'reject' })).status, 400)
    assert.equal((await request(`/rfqs/${rfq.id}/quotes/SUP-001`, { lines: [{ lineId: rfq.lines[0].lineId, rate: 999 }] }, 'PUT')).status, 409)
    assert.equal((await request(`/rfqs/${rfq.id}/status`, { status: 'Draft' })).status, 409)
  })
  await t.test('recommendation validates weights and fails visibly without AI', async () => {
    assert.equal((await request('/rfqs/RFQ-2026-0042/recommend', { weights: { price: 0, quality: 0, delivery: 0 } })).status, 400)
    assert.equal((await request('/rfqs/RFQ-2026-0042/recommend', { weights: { price: 100, quality: 0, delivery: 0 } })).status, 503)
  })
  await t.test('diagnostics correlate failed requests and record sanitized UI events', async () => {
    const failed = await request(`/rfqs/${rfq.id}/award`, { supplierId: 'SUP-001' })
    assert.ok(failed.requestId)
    const logs = await request(`/logs?q=${failed.requestId}`, null, 'GET')
    assert.equal(logs.data.entries.length, 1)
    assert.equal(logs.data.entries[0].status, failed.status)
    assert.equal(logs.data.entries[0].level, 'warn')
    assert.equal((await request('/logs/events', { events: [{ event: 'ui.click', message: 'Save password=secret', path: '/award' }] })).data.recorded, 1)
    const clicks = await request('/logs?q=ui.click', null, 'GET')
    assert.ok(!JSON.stringify(clicks.data.entries).includes('secret'))
    assert.equal(clicks.data.policy.maxEntries, 20000)
    assert.equal((await request('/logs/events', { events: Array(26).fill({ event: 'ui.click' }) })).status, 400)
  })
})
